name: data
description: "A new Flutter package project."
version: 0.0.1
homepage:
repository: https://github.com/CodeHiSmile/data
issue_tracker: https://github.com/CodeHiSmile/data/issues
documentation: https://github.com/CodeHiSmile/data

environment:
  sdk: ^3.10.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  intl: ^0.18.1
  get_it: ^9.0.5
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  injectable: ^2.5.1
  alice: ^1.0.0
  alice_dio: ^1.0.7
  gql: ^1.0.1
  dartx: ^1.2.0
  shared_preferences: ^2.5.3
  encrypt_shared_preferences: ^0.9.10

  shared:
    path: ../shared
  domain:
    path: ../domain

#  shared:
#    git:
#      url: https://github.com/CodeHiSmile/shared
#      ref: main
#  domain:
#    git:
#      url: https://github.com/CodeHiSmile/domain
#      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.3
  json_serializable: ^6.11.1
  flutter_gen_runner: ^5.12.0
  freezed: ^3.2.3
  injectable_generator: ^2.7.0

flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
